Sugate/fix stop vmm
firecracker-microvm/firecracker-go-sdk pull request #429
Opened 2022-07-29 09:17 UTC by Joffref

Closes: #428

*Description of changes:* add a cleanup chan to ensure cleanup is waited by the stopVMM method.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-29 16:49 UTC, ginglis13 commented
Hi @Joffref , thanks for the PR! Could you please add DCO to your commits by signing them `git commit -s`?

2022-07-29 20:20 UTC, Joffref commented
Is this good @ginglis13 ?

2022-07-29 22:05 UTC, ginglis13 requested changes
small nitpick, otherwise LGTM

2022-07-30 09:51 UTC, Joffref commented on machine_test.go
> +	require.NoError(t, err)
Change done ! I'm letting you close the comment :+1:

2022-08-01 17:06 UTC, ginglis13 commented
LGTM, thanks. 2 quick requests before we can merge this:

1/ Can you squash these 5 commits into one commit?

2/ Can you sign that commit using your full, real first and last name?

2022-08-29 17:59 UTC, ginglis13 approved these changes

2022-09-07 23:28 UTC, ginglis13 approved these changes
LGTM, GH actions tests failing having been fixed in main already.

2022-09-08 17:00 UTC, austinvazquez approved these changes

2022-09-08 17:01 UTC, merged