Removing CPU template as a runtime config where default T2 template i…
firecracker-microvm/firecracker-go-sdk pull request #456
Opened 2022-10-05 22:35 UTC by vvejell1

…s pinned in the config.

Signed-off-by: Vaishnavi Vejella <vvejella@amazon.com>

*Issue:* Intel T2 and C3 instance types are the only ones that support the CPU template. BuildKite's pipeline fails when I test an **AMD** instance against the Firecracker Go SDK. 
*Description of changes:* In this case, when CPUTemplate is not passed in the configuration files, the build succeeds but the tests fail due to [TestMicroVMExecution/TestUpdateBalloonStats](https://buildkite.com/firecracker-microvm/vvejella-firecracker-go-sdk-amd/builds/18#0183aa39-960f-47eb-9e0e-b9392ef33dab). 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-05 22:48 UTC, ginglis13 requested changes
some minor changes requested but otherwise LGTM, thanks!

Could you update your commit message to have the body be descriptive like the description you've provided in this PR?

2022-10-05 22:48 UTC, ginglis13 commented on client/models/machine_configuration.go
> -	// cpu template
I think we still want to keep the `CPUTemplate` as an option here to allows those that do wish to specify this value to do so. same goes for `Validate` and `validateCPUTemplate` functions

2022-10-06 00:07 UTC, kzys commented
Can you add one test specifically for CPUTemplate? We can disable the test on non-Intel platforms.

After merging this change, even if we break CPUTemplate, we wouldn't notice.

2022-10-10 16:39 UTC, kzys approved these changes

2022-10-10 16:41 UTC, kzys commented
@vvejell1 Can you change your name on the commit? You would need something like

```
% git config user.name 'Vaishnavi Vejella' 
% git commit --amend --reset-author 
```

to rewrite the name.

2022-10-10 18:18 UTC, merged